### ISSUE TITLE
unknown url_type

### ISSUE THREAD

**Issue by thundergreen** [ericmatte/HomeAutomation#4]
Hi! I was trying to get your app running but failed. here my error log and my config:

```
2019-10-02 23:09:35.106763 WARNING AppDaemon: Worker Ags: {'name': 'tv_lights_sync', 'id': UUID('9caef641-ebef-4dc0-bae5-1351c35fd8ef'), 'type': 'attr', 'function': <bound method tv_lights_sync.change_lights_color of <tv_lights_sync.tv_lights_sync object at 0x7f22e87d8048>>, 'attribute': 'entity_picture', 'entity': 'media_player.kodi', 'new_state': '/api/media_player_proxy/media_player.kodi?token=12b9d1795f5743b62d71b5e9cd116904c83cbb0a0277f34f477689c3487f42a9&cache=fd7ae725186a3703', 'old_state': None, 'kwargs': {'attribute': 'entity_picture', 'handle': UUID('9bac4006-83c7-4f7b-9d11-0cece377457e')}}
2019-10-02 23:09:35.106925 WARNING AppDaemon: ------------------------------------------------------------
2019-10-02 23:09:35.107492 WARNING AppDaemon: Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/appdaemon/appdaemon.py", line 595, in worker
    self.sanitize_state_kwargs(app, args["kwargs"]))
  File "/config/appdaemon/apps/tv_lights_sync.py", line 24, in change_lights_color
    rgb_colors = self.get_colors(newUrl)
  File "/config/appdaemon/apps/tv_lights_sync.py", line 35, in get_colors
    fd = urlopen(url)
  File "/usr/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 510, in open
    req = Request(fullurl, data)
  File "/usr/lib/python3.7/urllib/request.py", line 328, in __init__
    self.full_url = url
  File "/usr/lib/python3.7/urllib/request.py", line 354, in full_url
    self._parse()
  File "/usr/lib/python3.7/urllib/request.py", line 383, in _parse
    raise ValueError("unknown url type: %r" % self.full_url)
ValueError: unknown url type: '/api/media_player_proxy/media_player.kodi?token=12b9d1795f5743b62d71b5e9cd116904c83cbb0a0277f34f477689c3487f42a9&cache=fd7ae725186a3703'

2019-10-02 23:09:35.107671 WARNING AppDaemon: ------------------------------------------------------------
```

CONFIG: 

tv_lights_sync:
  module: tv_lights_sync
  class: tv_lights_sync
  ha_url: !secret ha_url
  media_player: media_player.kodi
  photo_attribute: "entity_picture"
  condition:
    entity: input_boolean.sync_tv_lights
    state: 'on'
  lights:
    - light.hyperion
```

SECRETS.YAML:

```
token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJmMzNhOTRmYTRmYTk0MzE4YThmMTlmMGM2MTc0YzA0NiIsImlhdCI6MTU2OTU5MDEyMiwiZXhwIjoxODg0OTUwMTIyfQ.7-V5EMb7ri1OZYjGNVX517uWYjkFnycla5nAJlJF4S0
ha_url: http://192.168.1.41:8123
```

**Comment by ericmatte** [comment]
Hi! It seems like the url `/api/media_player_proxy/media_player.kodi?token=...` sent to `urllib` is not valid.

For my setup, I am using this app for my Chromecast with HA available on an https public endpoint. I think that might be a reason why this is not working for you.

Could you try to setting up a public endpoint for you HA with something like [DuckDNS](https://www.home-assistant.io/addons/duckdns/)? And also change `ha_url` to that new url.

**Comment by ericmatte** [comment]
Closing due to inactivity. Feel free to reopen this issue if it is still not working.
