### ISSUE TITLE
url error

### ISSUE THREAD

**Issue by thundergreen** [ericmatte/HomeAutomation#6]
Hi.. it is not clear how to set the url of hass in the config. I have this format:

```yml
tv_lights_sync:
  module: tv_lights_sync
  class: tv_lights_sync
  ha_url: "http://192.168.1.41:8123" # Home Assistant Endpoint
  media_player: media_player.kodi
  photo_attribute: "entity_picture"
#  condition:
#    entity: input_boolean.sync_tv_lights
#    state: 'on'
  lights:
    - light.hyperion
    - light.led_strip_living_room
```
and get this error

```bash
2020-02-28 23:06:03.167312 WARNING tv_lights_sync: Worker Ags: {'id': '04dd5a15871e438aa132f5470ff88d25', 'name': 'tv_lights_sync', 'objectid': '995c96e6718b4a21a0fe8431bd8fd8d9', 'type': 'state', 'function': <bound method tv_lights_sync.change_lights_color of <tv_lights_sync.tv_lights_sync object at 0x7f1f4f51d850>>, 'attribute': 'entity_picture', 'entity': 'media_player.kodi', 'new_state': '/api/media_player_proxy/media_player.kodi?token=37e6569d373ad85b07814ee821eb8c988243d47b47d1715645783c9b73686162&cache=1ca48a2de4c42708', 'old_state': None, 'pin_app': True, 'pin_thread': 3, 'kwargs': {'attribute': 'entity_picture', '__thread_id': 'thread-3'}}

2020-02-28 23:06:03.167721 WARNING tv_lights_sync: ------------------------------------------------------------

2020-02-28 23:06:03.168501 WARNING tv_lights_sync: Traceback (most recent call last):

  File "/usr/lib/python3.8/site-packages/appdaemon/threading.py", line 777, in worker
    funcref(entity, attr, old_state, new_state,

  File "/config/appdaemon/apps/tv_lights_sync.py", line 24, in change_lights_color
    rgb_colors = self.get_colors(newUrl)

  File "/config/appdaemon/apps/tv_lights_sync.py", line 35, in get_colors
    fd = urlopen(url)

  File "/usr/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)

  File "/usr/lib/python3.8/urllib/request.py", line 509, in open
    req = Request(fullurl, data)

  File "/usr/lib/python3.8/urllib/request.py", line 328, in __init__
    self.full_url = url

  File "/usr/lib/python3.8/urllib/request.py", line 354, in full_url
    self._parse()

  File "/usr/lib/python3.8/urllib/request.py", line 383, in _parse
    raise ValueError("unknown url type: %r" % self.full_url)

ValueError: unknown url type: '/api/media_player_proxy/media_player.kodi?token=37e6569d373ad85b07814ee821eb8c988243d47b47d1715645783c9b73686162&cache=1ca48a2de4c42708'

2020-02-28 23:06:03.168883 WARNING tv_lights_sync: ------------------------------------------------------------
```

**Comment by thundergreen** [comment]
The link works and a file can be downloaded but it seems i have an error in my url?

**Comment by ericmatte** [comment]
Hi @thundergreen, I am currently using this appdaemon app with a ChromeCast device.

Did you tried what I've explained in my comment here? https://github.com/ericmatte/HomeAutomation/issues/4#issuecomment-538038233

I mostly think the error is due to the fact that `'/api/media_player_proxy/media_player.kodi?token=...` is a relative url and therefore, `urlopen` cannot find it.

Try to append the prefix of your url (`"http://192.168.1.41:8123"`) to the `url` param here: https://github.com/ericmatte/HomeAutomation/blob/835ca9e7d5b9fb84f3f126f309147959c9295022/appdaemon/conf/apps/tv_lights_sync.py#L35

**Comment by ericmatte** [comment]
Relates to https://github.com/ericmatte/HomeAutomation/issues/4

**Comment by thundergreen** [comment]
all right.. I will try and report... I actually have to figure out how to install the depedencies :P

**Comment by ericmatte** [comment]
**EDIT**: https://github.com/ericmatte/ad-media-lights-sync is now a default app in HACS, so there is no more need to add it as a custom repo.

@thundergreen I'm closing your issue, as I've moved the tv lights sync app into it's own repo: [**ericmatte/ad-media-lights-sync**](https://github.com/ericmatte/ad-media-lights-sync).

It is now compatible with HACS as a custom repository!

I added a section in the README.md with the dependency packages that I've used to make it work: https://github.com/ericmatte/ad-media-lights-sync#prerequisites

---
I'm also waiting for [hacs/default/pull/304](https://github.com/hacs/default/pull/304) to be merged in order to make the project a default repository in HACS.

**Comment by ericmatte** [comment]
Hi @thundergreen,

If your still having this issue, please refer to this: https://github.com/ericmatte/ad-media-lights-sync/issues/1.

I've added support for specifying your `ha_url` in your `apps.yaml` config, which should fix your issue.

**Comment by thundergreen** [comment]
![image](https://user-images.githubusercontent.com/13320319/79881976-31db4780-83f2-11ea-83b6-f1dbd82a40b1.png)

**Comment by ericmatte** [comment]
Sorry, I've forgot to let you know: there is no need to add it as a custom repositories anymore.
It is now available as a default app in HACS :) (since https://github.com/hacs/default/pull/304 has been merged)

Under `<your_ha_url>/hacs/appdaemon`

**Comment by ericmatte** [comment]
Sorry, I've forgot to let you know: there is no need to add it as a custom repositories anymore.
It is now available as a default app in HACS :) (since https://github.com/hacs/default/pull/304 has been merged)

Under `<your_ha_url>/hacs/appdaemon`
